version: '3.7'

services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: 'curso_laravel_vue'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3388:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - laravel

  # queue
  queue:
    image: especializati/laravel9-app
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
        - ./:/var/www
    depends_on:
        - redis
        - app
    networks:
      - laravel

  # redis
  redis:
    image: redis:latest
    networks:
    - laravel

networks:
    laravel:
        driver: bridge